from typing import List, TypedDict


class AgentState(TypedDict):
    # Core user query and notebook scope
    question: str
    notebook_id: str

    # Retrieved notes/document context string
    context: str

    # Flag indicating whether ChromaDB found context below the distance threshold
    has_relevant_context: bool

    # Final text response generated by Gemini or returned as fallback
    answer: str

    # List of metadata/sources used during retrieval
    sources_type: str